Add cypress map examples
aartyszko-stx/instantly-better-cypress pull request #4
Opened 2023-08-27 19:09 UTC by bbrozyna

2023-08-27 19:15 UTC, bbrozyna commented on cypress/support/commands.ts
> +Cypress.Commands.add(
I'm not using it after all. So we can remove it.  👎 or 👍

2023-08-27 19:16 UTC, bbrozyna commented on cypress/support/e2e.ts
> +import "./commands";
I assumed packages then inner ones order

2023-08-27 19:17 UTC, bbrozyna commented on package.json
> +  "dependencies": {
I added those as dependencies, because it doesn't match the template purposes and should be removed in that case :)

2023-08-29 20:58 UTC, aartyszko-stx requested changes

2023-08-29 20:58 UTC, aartyszko-stx commented on cypress/e2e/map.cy.ts
> +import { testExamples } from "@cypress/fiddle";
![image](https://github.com/aartyszko-stx/instantly-better-cypress/assets/138585233/017c180e-fab5-44f9-895f-bf680c07758e)

I'm getting typescript error that indicates it can't be imported as module :C

2023-08-29 20:58 UTC, aartyszko-stx commented on cypress/support/commands.ts
> +Cypress.Commands.add(
yup, let's remove it

2023-08-29 20:58 UTC, aartyszko-stx commented on cypress/e2e/map.cy.ts
> +import { testExamples } from "@cypress/fiddle";
we agree to leave it for later

2023-08-29 20:58 UTC, aartyszko-stx commented on cypress/e2e/chai-example.cy.ts
> +      .and("have.text", "Users")
this text assertion suppost to fail, right?

2023-08-30 15:57 UTC, aartyszko-stx approved these changes

2023-08-30 15:57 UTC, merged